import React, { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { ArrowLeft, Plus, Trash2, CheckCircle, HelpCircle, Save, Send, Sparkles, RefreshCw, AlertTriangle } from "lucide-react";
import "./TeacherCourseDetails.css";

const API_URL = "http://localhost:5000/api";

export default function CreateQuiz() {
  const { courseId } = useParams();
  const navigate = useNavigate();

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [instructions, setInstructions] = useState("");
  const [durationMinutes, setDurationMinutes] = useState(30);
  const [maxAttempts, setMaxAttempts] = useState(1);
  const [startAt, setStartAt] = useState("");
  const [endAt, setEndAt] = useState("");
  const [randomizeQuestions, setRandomizeQuestions] = useState(false);
  const [showAnswersAfterSubmission, setShowAnswersAfterSubmission] = useState(true);

  const [questions, setQuestions] = useState([
    {
      id: Date.now(),
      questionText: "",
      questionType: "mcq",
      options: ["Option 1", "Option 2", "Option 3", "Option 4"],
      correctAnswer: "Option 1",
      marks: 1.0,
    },
  ]);

  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  // --- AI Quiz Generator State ---
  const [courseMaterials, setCourseMaterials] = useState([]);
  const [loadingMaterials, setLoadingMaterials] = useState(false);
  const [selectedMaterialIds, setSelectedMaterialIds] = useState([]);

  const [aiQuestionCount, setAiQuestionCount] = useState(10);
  const [aiDifficulty, setAiDifficulty] = useState("medium");
  const [aiQuestionTypes, setAiQuestionTypes] = useState(["mcq"]);
  const [aiTopic, setAiTopic] = useState("");
  const [aiMarks, setAiMarks] = useState(1.0);

  const [isGeneratingAi, setIsGeneratingAi] = useState(false);
  const [aiProgressStep, setAiProgressStep] = useState(0);
  const [aiSuccessMessage, setAiSuccessMessage] = useState("");
  const [aiError, setAiError] = useState("");
  const [aiTopicError, setAiTopicError] = useState(null);
  const [regeneratingQId, setRegeneratingQId] = useState(null);

  useEffect(() => {
    const fetchMaterials = async () => {
      if (!courseId) return;
      try {
        setLoadingMaterials(true);
        const res = await fetch(`${API_URL}/materials/course/${courseId}`);
        const data = await res.json();
        if (data.success && Array.isArray(data.data)) {
          setCourseMaterials(data.data);
          if (data.data.length > 0) {
            setSelectedMaterialIds([String(data.data[0].id)]);
          }
        }
      } catch (err) {
        console.error("Error fetching course materials:", err);
      } finally {
        setLoadingMaterials(false);
      }
    };
    fetchMaterials();
  }, [courseId]);

  const handleGenerateAiQuiz = async () => {
    try {
      setAiError("");
      setAiSuccessMessage("");
      setAiTopicError(null);

      if (selectedMaterialIds.length === 0) {
        setAiError("Please select at least one course material.");
        return;
      }

      setIsGeneratingAi(true);
      setAiProgressStep(1);

      await new Promise((r) => setTimeout(r, 400));
      setAiProgressStep(2);

      await new Promise((r) => setTimeout(r, 400));
      setAiProgressStep(3);

      const token = localStorage.getItem("token");
      const res = await fetch(`${API_URL}/teacher/courses/${courseId}/quizzes/generate`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          courseId,
          materialIds: selectedMaterialIds,
          questionCount: aiQuestionCount,
          difficulty: aiDifficulty,
          questionTypes: aiQuestionTypes,
          topic: aiTopic,
          marks: aiMarks,
        }),
      });

      setAiProgressStep(4);
      const data = await res.json();

      if (!res.ok || !data.success) {
        if (data.code === "INSUFFICIENT_TOPIC_CONTENT") {
          setAiTopicError({
            topic: data.topic || aiTopic,
            reason: data.reason || "The selected materials do not contain sufficient information about this topic.",
            score: data.coverageScore || 0
          });
          return;
        }
        throw new Error(data.message || "Unable to generate the quiz. Please try again.");
      }

      const newGenQuestions = data.questions || [];
      if (newGenQuestions.length === 0) {
        throw new Error("No questions were generated by the AI model.");
      }

      if (questions.length === 1 && !questions[0].questionText.trim()) {
        setQuestions(newGenQuestions);
      } else {
        setQuestions([...questions, ...newGenQuestions]);
      }

      setAiSuccessMessage(`${newGenQuestions.length} grounded questions generated successfully based strictly on your source materials.`);
    } catch (err) {
      setAiError(err.message || "Unable to generate the quiz. Please try again.");
    } finally {
      setIsGeneratingAi(false);
      setAiProgressStep(0);
    }
  };

  const handleRegenerateSingleQuestion = async (qIndex) => {
    const targetQ = questions[qIndex];
    if (!targetQ) return;

    if (selectedMaterialIds.length === 0) {
      setAiError("Please select at least one course material first.");
      return;
    }

    try {
      setRegeneratingQId(targetQ.id);
      const token = localStorage.getItem("token");

      const res = await fetch(`${API_URL}/teacher/courses/${courseId}/quizzes/generate-single`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          courseId,
          materialIds: selectedMaterialIds,
          originalQuestion: targetQ.questionText,
          difficulty: aiDifficulty,
          questionType: targetQ.questionType || "mcq",
          topic: aiTopic,
          marks: targetQ.marks || aiMarks,
        }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.message || "Failed to regenerate single question.");
      }

      if (data.question) {
        const updated = [...questions];
        updated[qIndex] = {
          ...data.question,
          id: targetQ.id,
        };
        setQuestions(updated);
      }
    } catch (err) {
      alert(err.message || "Regenerate single question failed.");
    } finally {
      setRegeneratingQId(null);
    }
  };

  const handleAddQuestion = (type = "mcq") => {
    const newQ = {
      id: Date.now(),
      questionText: "",
      questionType: type,
      options: type === "mcq" || type === "multiple_select" ? ["Option 1", "Option 2", "Option 3", "Option 4"] : type === "true_false" ? ["True", "False"] : [],
      correctAnswer: type === "mcq" ? "Option 1" : type === "multiple_select" ? ["Option 1"] : type === "true_false" ? "True" : "",
      marks: 1.0,
    };
    setQuestions([...questions, newQ]);
  };

  const handleUpdateQuestion = (index, field, value) => {
    const updated = [...questions];
    updated[index][field] = value;
    setQuestions(updated);
  };

  const handleUpdateOption = (qIndex, optIndex, value) => {
    const updated = [...questions];
    const oldVal = updated[qIndex].options[optIndex];
    updated[qIndex].options[optIndex] = value;

    if (updated[qIndex].questionType === "mcq") {
      if (updated[qIndex].correctAnswer === oldVal) {
        updated[qIndex].correctAnswer = value;
      }
    } else if (updated[qIndex].questionType === "multiple_select") {
      if (Array.isArray(updated[qIndex].correctAnswer)) {
        updated[qIndex].correctAnswer = updated[qIndex].correctAnswer.map((opt) =>
          opt === oldVal ? value : opt
        );
      }
    }

    setQuestions(updated);
  };

  const handleRemoveQuestion = (index) => {
    if (questions.length === 1) return;
    setQuestions(questions.filter((_, i) => i !== index));
  };

  const calculatedTotalMarks = questions.reduce((sum, q) => sum + (parseFloat(q.marks) || 0), 0);

  const handleSubmitQuiz = async (statusToSet) => {
    try {
      setError("");
      if (!title.trim()) {
        setError("Please enter a quiz title.");
        return;
      }

      if (statusToSet === "published") {
        if (questions.length === 0) {
          setError("Cannot publish a quiz with zero questions.");
          return;
        }
        for (let i = 0; i < questions.length; i++) {
          if (!questions[i].questionText.trim()) {
            setError(`Question ${i + 1} text is required.`);
            return;
          }
        }
      }

      setLoading(true);
      const token = localStorage.getItem("token");

      const response = await fetch(`${API_URL}/teacher/courses/${courseId}/quizzes`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          title,
          description,
          instructions,
          durationMinutes,
          maxAttempts,
          startAt: startAt || null,
          endAt: endAt || null,
          randomizeQuestions,
          showAnswersAfterSubmission,
          status: statusToSet,
          questions,
        }),
      });

      const result = await response.json();
      if (!response.ok || !result.success) {
        throw new Error(result.message || "Failed to create quiz.");
      }

      navigate(`/teacher/courses/${courseId}`);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="tcd-page">
      <header className="tcd-header">
        <button className="tcd-back" onClick={() => navigate(-1)}>
          <ArrowLeft size={18} /> Back to Course Details
        </button>
        <h2>Create New Quiz</h2>
      </header>

      {error && (
        <div style={{ background: "rgba(239, 68, 68, 0.15)", color: "#f87171", padding: "1rem", borderRadius: "10px", marginBottom: "1.5rem" }}>
          ⚠️ {error}
        </div>
      )}

      <div className="tcd-overview-grid">
        {/* Quiz Meta Form */}
        <div className="tcd-panel">
          <h3>Quiz Details</h3>
          <div style={{ display: "flex", flexDirection: "column", gap: "1rem" }}>
            <div>
              <label style={{ display: "block", color: "#9292a5", fontSize: "12px", marginBottom: "4px" }}>Quiz Title *</label>
              <input
                type="text"
                placeholder="e.g. Mid-Term Assessment"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                style={{ width: "100%", padding: "10px", background: "#15151f", border: "1px solid #30303e", borderRadius: "8px", color: "white" }}
              />
            </div>

            <div>
              <label style={{ display: "block", color: "#9292a5", fontSize: "12px", marginBottom: "4px" }}>Description</label>
              <textarea
                rows={2}
                placeholder="Short quiz description..."
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                style={{ width: "100%", padding: "10px", background: "#15151f", border: "1px solid #30303e", borderRadius: "8px", color: "white" }}
              />
            </div>

            <div>
              <label style={{ display: "block", color: "#9292a5", fontSize: "12px", marginBottom: "4px" }}>Instructions</label>
              <textarea
                rows={2}
                placeholder="Instructions for students before starting..."
                value={instructions}
                onChange={(e) => setInstructions(e.target.value)}
                style={{ width: "100%", padding: "10px", background: "#15151f", border: "1px solid #30303e", borderRadius: "8px", color: "white" }}
              />
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
              <div>
                <label style={{ display: "block", color: "#9292a5", fontSize: "12px", marginBottom: "4px" }}>Duration (Minutes)</label>
                <input
                  type="number"
                  value={durationMinutes}
                  onChange={(e) => setDurationMinutes(e.target.value)}
                  style={{ width: "100%", padding: "10px", background: "#15151f", border: "1px solid #30303e", borderRadius: "8px", color: "white" }}
                />
              </div>
              <div>
                <label style={{ display: "block", color: "#9292a5", fontSize: "12px", marginBottom: "4px" }}>Max Attempts</label>
                <input
                  type="number"
                  value={maxAttempts}
                  onChange={(e) => setMaxAttempts(e.target.value)}
                  style={{ width: "100%", padding: "10px", background: "#15151f", border: "1px solid #30303e", borderRadius: "8px", color: "white" }}
                />
              </div>
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1rem" }}>
              <div>
                <label style={{ display: "block", color: "#9292a5", fontSize: "12px", marginBottom: "4px" }}>Start Date & Time</label>
                <input
                  type="datetime-local"
                  value={startAt}
                  onChange={(e) => setStartAt(e.target.value)}
                  style={{ width: "100%", padding: "10px", background: "#15151f", border: "1px solid #30303e", borderRadius: "8px", color: "white" }}
                />
              </div>
              <div>
                <label style={{ display: "block", color: "#9292a5", fontSize: "12px", marginBottom: "4px" }}>Due Date & Time</label>
                <input
                  type="datetime-local"
                  value={endAt}
                  onChange={(e) => setEndAt(e.target.value)}
                  style={{ width: "100%", padding: "10px", background: "#15151f", border: "1px solid #30303e", borderRadius: "8px", color: "white" }}
                />
              </div>
            </div>

            <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem", marginTop: "0.5rem" }}>
              <label style={{ display: "flex", alignItems: "center", gap: "8px", color: "#c5c5d1", fontSize: "13px", cursor: "pointer" }}>
                <input type="checkbox" checked={randomizeQuestions} onChange={(e) => setRandomizeQuestions(e.target.checked)} />
                Randomize question order
              </label>
              <label style={{ display: "flex", alignItems: "center", gap: "8px", color: "#c5c5d1", fontSize: "13px", cursor: "pointer" }}>
                <input type="checkbox" checked={showAnswersAfterSubmission} onChange={(e) => setShowAnswersAfterSubmission(e.target.checked)} />
                Show correct answers after submission
              </label>
            </div>
          </div>
        </div>

        {/* Summary Card & Submit */}
        <div className="tcd-panel" style={{ height: "fit-content" }}>
          <h3>Quiz Summary</h3>
          <div className="tcd-info-row">
            <span>Total Questions</span>
            <strong>{questions.length}</strong>
          </div>
          <div className="tcd-info-row">
            <span>Total Calculated Marks</span>
            <strong>{calculatedTotalMarks} pts</strong>
          </div>
          <div className="tcd-info-row">
            <span>Duration</span>
            <strong>{durationMinutes} mins</strong>
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem", marginTop: "1.5rem" }}>
            <button
              className="tcd-primary-btn"
              disabled={loading}
              onClick={() => handleSubmitQuiz("published")}
              style={{ justifyContent: "center", background: "#7652d6" }}
            >
              <Send size={16} /> Publish Quiz
            </button>
            <button
              className="tcd-primary-btn"
              disabled={loading}
              onClick={() => handleSubmitQuiz("draft")}
              style={{ justifyContent: "center", background: "#292938" }}
            >
              <Save size={16} /> Save as Draft
            </button>
          </div>
        </div>
      </div>

      {/* AI Quiz Generator Section */}
      <section
        style={{
          marginTop: "2.5rem",
          background: "linear-gradient(145deg, rgba(24, 16, 46, 0.95), rgba(13, 9, 26, 0.98))",
          border: "1px solid rgba(168, 85, 247, 0.35)",
          borderRadius: "20px",
          padding: "1.75rem",
          boxShadow: "0 12px 40px -10px rgba(147, 51, 234, 0.22), inset 0 1px 0 rgba(255, 255, 255, 0.1)",
          backdropFilter: "blur(12px)",
          position: "relative",
          overflow: "hidden"
        }}
      >
        {/* Subtle Ambient Light Glow */}
        <div
          style={{
            position: "absolute",
            top: "-50px",
            right: "-50px",
            width: "250px",
            height: "250px",
            background: "radial-gradient(circle, rgba(168, 85, 247, 0.18) 0%, transparent 70%)",
            pointerEvents: "none"
          }}
        />

        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1.5rem" }}>
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
              <div
                style={{
                  width: "38px",
                  height: "38px",
                  borderRadius: "10px",
                  background: "linear-gradient(135deg, #a855f7, #6366f1)",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  boxShadow: "0 4px 14px rgba(168, 85, 247, 0.4)"
                }}
              >
                <Sparkles size={20} color="#ffffff" />
              </div>
              <div>
                <div style={{ display: "flex", alignItems: "center", gap: "0.6rem" }}>
                  <h2 style={{ fontSize: "1.5rem", margin: 0, color: "#ffffff", fontWeight: 700, letterSpacing: "-0.5px" }}>
                    AI Quiz Generator
                  </h2>
                  <span
                    style={{
                      background: "rgba(168, 85, 247, 0.15)",
                      border: "1px solid rgba(168, 85, 247, 0.4)",
                      color: "#c084fc",
                      fontSize: "11px",
                      fontWeight: 600,
                      padding: "3px 10px",
                      borderRadius: "20px",
                      display: "flex",
                      alignItems: "center",
                      gap: "5px"
                    }}
                  >
                    <span style={{ width: "6px", height: "6px", borderRadius: "50%", background: "#a855f7", display: "inline-block", boxShadow: "0 0 8px #a855f7" }} />
                    Powered by Gemini 3.5
                  </span>
                </div>
                <p style={{ color: "#94a3b8", fontSize: "13.5px", marginTop: "4px", marginBottom: 0 }}>
                  Generate custom, curriculum-aligned quiz questions directly from your course materials.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Source Materials Selection */}
        <div style={{ background: "rgba(18, 13, 36, 0.8)", border: "1px solid rgba(67, 46, 114, 0.6)", borderRadius: "14px", padding: "1.25rem", marginBottom: "1.5rem" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1rem" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
              <span style={{ color: "#e2e8f0", fontWeight: 600, fontSize: "14px" }}>
                Select Source Materials
              </span>
              <span style={{ background: "rgba(168, 85, 247, 0.2)", color: "#d8b4fe", fontSize: "11.5px", padding: "2px 8px", borderRadius: "12px", fontWeight: 600 }}>
                {selectedMaterialIds.length} Selected
              </span>
            </div>
            {courseMaterials.length > 0 && (
              <div style={{ display: "flex", gap: "1rem" }}>
                <button
                  type="button"
                  onClick={() => setSelectedMaterialIds(courseMaterials.map((m) => String(m.id)))}
                  style={{ background: "none", border: "none", color: "#c084fc", fontSize: "12.5px", cursor: "pointer", fontWeight: 600, transition: "color 0.2s" }}
                >
                  Select All
                </button>
                <span style={{ color: "#475569" }}>|</span>
                <button
                  type="button"
                  onClick={() => setSelectedMaterialIds([])}
                  style={{ background: "none", border: "none", color: "#94a3b8", fontSize: "12.5px", cursor: "pointer", fontWeight: 500 }}
                >
                  Deselect All
                </button>
              </div>
            )}
          </div>

          {loadingMaterials ? (
            <div style={{ padding: "1.5rem", textAlign: "center", color: "#94a3b8", fontSize: "13px" }}>
              <RefreshCw size={18} style={{ animation: "spin 1s linear infinite", marginBottom: "8px" }} />
              <div>Fetching course materials...</div>
            </div>
          ) : courseMaterials.length === 0 ? (
            <div style={{ padding: "1.25rem", textAlign: "center", color: "#94a3b8", fontSize: "13px", background: "#0f0b1f", borderRadius: "10px", border: "1px dashed #2d2047" }}>
              📄 No course materials uploaded yet for this course. Please upload PDF or document materials to enable AI question generation.
            </div>
          ) : (
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: "0.85rem" }}>
              {courseMaterials.map((material) => {
                const matIdStr = String(material.id);
                const isSelected = selectedMaterialIds.includes(matIdStr);
                return (
                  <div
                    key={material.id}
                    onClick={() => {
                      if (isSelected) {
                        setSelectedMaterialIds(selectedMaterialIds.filter((id) => id !== matIdStr));
                      } else {
                        setSelectedMaterialIds([...selectedMaterialIds, matIdStr]);
                      }
                    }}
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "0.85rem",
                      padding: "12px 14px",
                      borderRadius: "10px",
                      background: isSelected
                        ? "linear-gradient(135deg, rgba(168, 85, 247, 0.2), rgba(118, 82, 214, 0.1))"
                        : "#0f0b1f",
                      border: isSelected ? "1.5px solid #a855f7" : "1px solid #281d42",
                      boxShadow: isSelected ? "0 4px 16px rgba(168, 85, 247, 0.25)" : "none",
                      cursor: "pointer",
                      transition: "all 0.2s cubic-bezier(0.4, 0, 0.2, 1)",
                      userSelect: "none"
                    }}
                  >
                    <div
                      style={{
                        width: "22px",
                        height: "22px",
                        borderRadius: "6px",
                        background: isSelected ? "#a855f7" : "#1a142e",
                        border: isSelected ? "none" : "1.5px solid #4a386c",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                        flexShrink: 0,
                        transition: "all 0.2s ease"
                      }}
                    >
                      {isSelected && <CheckCircle size={15} color="#ffffff" />}
                    </div>

                    <div style={{ overflow: "hidden", flex: 1 }}>
                      <div style={{ color: isSelected ? "#ffffff" : "#cbd5e1", fontSize: "13.5px", fontWeight: 600, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>
                        {material.title || material.filename}
                      </div>
                      <div style={{ color: isSelected ? "#c084fc" : "#64748b", fontSize: "11px", marginTop: "2px", fontWeight: 500 }}>
                        {(material.file_type || material.filename?.split(".").pop() || "DOC").toUpperCase()} • Ready for AI
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Options Grid */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "1.25rem", marginBottom: "1.5rem" }}>
          {/* Question Count Pills */}
          <div>
            <label style={{ display: "block", color: "#cbd5e1", fontSize: "12.5px", marginBottom: "8px", fontWeight: 600 }}>
              Number of Questions
            </label>
            <div style={{ display: "flex", background: "#110c22", padding: "4px", borderRadius: "10px", border: "1px solid #281d42", gap: "4px" }}>
              {[5, 10, 15, 20].map((num) => (
                <button
                  key={num}
                  type="button"
                  onClick={() => setAiQuestionCount(num)}
                  style={{
                    flex: 1,
                    padding: "8px 0",
                    borderRadius: "7px",
                    border: "none",
                    background: aiQuestionCount === num ? "linear-gradient(135deg, #a855f7, #7652d6)" : "transparent",
                    color: aiQuestionCount === num ? "#ffffff" : "#94a3b8",
                    fontWeight: aiQuestionCount === num ? "700" : "500",
                    fontSize: "13px",
                    cursor: "pointer",
                    boxShadow: aiQuestionCount === num ? "0 4px 12px rgba(168, 85, 247, 0.35)" : "none",
                    transition: "all 0.2s ease"
                  }}
                >
                  {num}
                </button>
              ))}
            </div>
          </div>

          {/* Difficulty Pills */}
          <div>
            <label style={{ display: "block", color: "#cbd5e1", fontSize: "12.5px", marginBottom: "8px", fontWeight: 600 }}>
              Difficulty Level
            </label>
            <div style={{ display: "flex", background: "#110c22", padding: "4px", borderRadius: "10px", border: "1px solid #281d42", gap: "4px" }}>
              {["easy", "medium", "hard"].map((diff) => (
                <button
                  key={diff}
                  type="button"
                  onClick={() => setAiDifficulty(diff)}
                  style={{
                    flex: 1,
                    padding: "8px 0",
                    borderRadius: "7px",
                    border: "none",
                    background: aiDifficulty === diff ? "linear-gradient(135deg, #a855f7, #7652d6)" : "transparent",
                    color: aiDifficulty === diff ? "#ffffff" : "#94a3b8",
                    fontWeight: aiDifficulty === diff ? "700" : "500",
                    fontSize: "12.5px",
                    textTransform: "capitalize",
                    cursor: "pointer",
                    boxShadow: aiDifficulty === diff ? "0 4px 12px rgba(168, 85, 247, 0.35)" : "none",
                    transition: "all 0.2s ease"
                  }}
                >
                  {diff}
                </button>
              ))}
            </div>
          </div>

          {/* Topic Focus */}
          <div>
            <label style={{ display: "block", color: "#cbd5e1", fontSize: "12.5px", marginBottom: "8px", fontWeight: 600 }}>
              Specific Topic / Focus (Optional)
            </label>
            <input
              type="text"
              placeholder="e.g. Hive Architecture, Query Flow"
              value={aiTopic}
              onChange={(e) => setAiTopic(e.target.value)}
              style={{
                width: "100%",
                padding: "9.5px 12px",
                background: "#110c22",
                border: "1px solid #281d42",
                borderRadius: "10px",
                color: "#ffffff",
                fontSize: "13px",
                outline: "none",
                transition: "border 0.2s ease"
              }}
            />
          </div>

          {/* Default Marks */}
          <div>
            <label style={{ display: "block", color: "#cbd5e1", fontSize: "12.5px", marginBottom: "8px", fontWeight: 600 }}>
              Marks Per Question
            </label>
            <input
              type="number"
              step="0.5"
              value={aiMarks}
              onChange={(e) => setAiMarks(parseFloat(e.target.value) || 1)}
              style={{
                width: "100%",
                padding: "9.5px 12px",
                background: "#110c22",
                border: "1px solid #281d42",
                borderRadius: "10px",
                color: "#ffffff",
                fontSize: "13px",
                outline: "none"
              }}
            />
          </div>
        </div>

        {/* Question Types Checkboxes / Interactive Tags */}
        <div style={{ marginBottom: "1.5rem" }}>
          <label style={{ display: "block", color: "#cbd5e1", fontSize: "12.5px", marginBottom: "8px", fontWeight: 600 }}>
            Question Types to Include
          </label>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "0.6rem" }}>
            {[
              { id: "mcq", label: "Multiple Choice (MCQ)" },
              { id: "multiple_select", label: "Multi-Select" },
              { id: "true_false", label: "True / False" },
              { id: "short_answer", label: "Short Answer" }
            ].map((typeObj) => {
              const isChecked = aiQuestionTypes.includes(typeObj.id);
              return (
                <button
                  key={typeObj.id}
                  type="button"
                  onClick={() => {
                    if (isChecked) {
                      if (aiQuestionTypes.length > 1) {
                        setAiQuestionTypes(aiQuestionTypes.filter((t) => t !== typeObj.id));
                      }
                    } else {
                      setAiQuestionTypes([...aiQuestionTypes, typeObj.id]);
                    }
                  }}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "8px",
                    padding: "8px 14px",
                    borderRadius: "20px",
                    border: isChecked ? "1px solid #a855f7" : "1px solid #281d42",
                    background: isChecked ? "rgba(168, 85, 247, 0.2)" : "#110c22",
                    color: isChecked ? "#ffffff" : "#94a3b8",
                    fontSize: "12.5px",
                    fontWeight: isChecked ? 600 : 500,
                    cursor: "pointer",
                    transition: "all 0.2s ease"
                  }}
                >
                  <span
                    style={{
                      width: "16px",
                      height: "16px",
                      borderRadius: "50%",
                      background: isChecked ? "#a855f7" : "transparent",
                      border: isChecked ? "none" : "1.5px solid #475569",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      fontSize: "10px",
                      color: "#white"
                    }}
                  >
                    {isChecked ? "✓" : ""}
                  </span>
                  {typeObj.label}
                </button>
              );
            })}
          </div>
        </div>

        {/* Topic Error Banner (Insufficient Material) */}
        {aiTopicError && (
          <div
            style={{
              background: "rgba(239, 68, 68, 0.12)",
              border: "1.5px solid #ef4444",
              borderRadius: "14px",
              padding: "1.25rem 1.5rem",
              marginBottom: "1.5rem",
              boxShadow: "0 8px 24px rgba(239, 68, 68, 0.15)"
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: "10px", color: "#f87171", fontWeight: 700, fontSize: "15px", marginBottom: "8px" }}>
              <AlertTriangle size={22} />
              <span>⚠️ Insufficient Material for Topic</span>
            </div>
            <div style={{ color: "#fca5a5", fontSize: "13.5px", lineHeight: "1.6", marginBottom: "8px" }}>
              The selected materials do not contain sufficient educational content about:
              <div style={{ background: "rgba(0,0,0,0.35)", padding: "4px 12px", borderRadius: "6px", color: "#ffffff", fontWeight: 700, display: "inline-block", margin: "6px 0 8px 8px", border: "1px solid rgba(239, 68, 68, 0.3)" }}>
                "{aiTopicError.topic}"
              </div>
            </div>
            <div style={{ background: "rgba(239, 68, 68, 0.18)", borderLeft: "4px solid #f87171", padding: "10px 14px", borderRadius: "0 8px 8px 0", color: "#fee2e2", fontSize: "13px", marginBottom: "12px" }}>
              <strong>Reason:</strong> {aiTopicError.reason}
            </div>
            <div style={{ color: "#cbd5e1", fontSize: "12.5px" }}>
              💡 <strong>Suggestion:</strong> Try entering a topic supported by the material (e.g. Hive Architecture, HDFS Commands) or upload additional course material.
            </div>
          </div>
        )}

        {/* Error / Success Banners */}
        {aiError && (
          <div style={{ background: "rgba(239, 68, 68, 0.15)", border: "1px solid #ef4444", color: "#f87171", padding: "0.85rem 1.2rem", borderRadius: "10px", marginBottom: "1.25rem", fontSize: "13.5px" }}>
            ⚠️ {aiError}
          </div>
        )}
        {aiSuccessMessage && (
          <div style={{ background: "rgba(34, 197, 94, 0.15)", border: "1px solid #22c55e", color: "#4ade80", padding: "0.85rem 1.2rem", borderRadius: "10px", marginBottom: "1.25rem", fontSize: "13.5px", display: "flex", alignItems: "center", gap: "8px" }}>
            <CheckCircle size={18} /> {aiSuccessMessage}
          </div>
        )}

        {/* Progress Stepper Loading UI */}
        {isGeneratingAi && (
          <div style={{ background: "rgba(17, 12, 34, 0.95)", border: "1px solid #7652d6", borderRadius: "14px", padding: "1.25rem", marginBottom: "1.5rem", boxShadow: "0 8px 30px rgba(118, 82, 214, 0.3)" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1rem" }}>
              <div style={{ color: "#e9d5ff", fontWeight: 700, fontSize: "14px", display: "flex", alignItems: "center", gap: "10px" }}>
                <RefreshCw size={18} style={{ animation: "spin 1s linear infinite", color: "#c084fc" }} />
                <span>Generating Quiz Questions via Gemini AI...</span>
              </div>
              <span style={{ color: "#c084fc", fontSize: "12px", fontWeight: 600 }}>
                Step {aiProgressStep} of 4 ({aiProgressStep * 25}%)
              </span>
            </div>

            {/* Glowing Animated Bar */}
            <div style={{ width: "100%", height: "6px", background: "#1f1838", borderRadius: "10px", overflow: "hidden", marginBottom: "1.25rem" }}>
              <div
                style={{
                  width: `${aiProgressStep * 25}%`,
                  height: "100%",
                  background: "linear-gradient(90deg, #a855f7, #6366f1)",
                  borderRadius: "10px",
                  transition: "width 0.4s ease",
                  boxShadow: "0 0 10px #a855f7"
                }}
              />
            </div>

            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: "10px" }}>
              {[
                { step: 1, label: "1. Reading Materials" },
                { step: 2, label: "2. Analyzing Topics" },
                { step: 3, label: "3. Generating Options" },
                { step: 4, label: "4. Formatting Quiz" }
              ].map((s) => {
                const isCompleted = aiProgressStep > s.step;
                const isCurrent = aiProgressStep === s.step;
                return (
                  <div
                    key={s.step}
                    style={{
                      padding: "10px 8px",
                      borderRadius: "8px",
                      background: isCurrent
                        ? "linear-gradient(135deg, rgba(168, 85, 247, 0.3), rgba(99, 102, 241, 0.2))"
                        : isCompleted
                        ? "rgba(34, 197, 94, 0.12)"
                        : "#140f28",
                      border: isCurrent
                        ? "1.5px solid #a855f7"
                        : isCompleted
                        ? "1px solid #22c55e"
                        : "1px solid #251b3d",
                      color: isCurrent ? "#ffffff" : isCompleted ? "#4ade80" : "#64748b",
                      fontSize: "12px",
                      textAlign: "center",
                      fontWeight: isCurrent || isCompleted ? 600 : 400,
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                      gap: "6px"
                    }}
                  >
                    {isCompleted ? "✓ " : ""}{s.label}
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Generate Action Button */}
        <div style={{ display: "flex", justifyContent: "flex-end" }}>
          <button
            type="button"
            className="tcd-primary-btn"
            disabled={isGeneratingAi || selectedMaterialIds.length === 0}
            onClick={handleGenerateAiQuiz}
            style={{
              background: isGeneratingAi
                ? "#3b2c60"
                : "linear-gradient(135deg, #a855f7 0%, #7652d6 50%, #6366f1 100%)",
              padding: "12px 30px",
              fontSize: "14.5px",
              fontWeight: 700,
              borderRadius: "12px",
              boxShadow: isGeneratingAi ? "none" : "0 6px 24px rgba(168, 85, 247, 0.45)",
              cursor: isGeneratingAi || selectedMaterialIds.length === 0 ? "not-allowed" : "pointer",
              transition: "all 0.25 ease"
            }}
          >
            <Sparkles size={18} /> {isGeneratingAi ? "Generating Questions..." : "✨ Generate Quiz"}
          </button>
        </div>
      </section>

      {/* Question Builder */}
      <section className="tcd-content" style={{ marginTop: "2rem" }}>
        <div className="tcd-section-heading">
          <div>
            <h2>Question Builder</h2>
            <p>Add and configure quiz questions ({questions.length} questions)</p>
          </div>
          <div style={{ display: "flex", gap: "0.5rem" }}>
            <button className="tcd-primary-btn" onClick={() => handleAddQuestion("mcq")}>+ Add MCQ</button>
            <button className="tcd-primary-btn" onClick={() => handleAddQuestion("multiple_select")}>+ Add Multi-Select</button>
            <button className="tcd-primary-btn" onClick={() => handleAddQuestion("true_false")}>+ True/False</button>
            <button className="tcd-primary-btn" onClick={() => handleAddQuestion("short_answer")}>+ Short Answer</button>
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
          {questions.map((q, qIndex) => (
            <div key={q.id} className="tcd-panel" style={{ position: "relative" }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1rem" }}>
                <strong>Question {qIndex + 1} ({q.questionType.toUpperCase()})</strong>
                <div style={{ display: "flex", alignItems: "center", gap: "0.75rem" }}>
                  <button
                    type="button"
                    onClick={() => handleRegenerateSingleQuestion(qIndex)}
                    disabled={regeneratingQId === q.id}
                    title="Regenerate this question with AI"
                    style={{
                      display: "flex",
                      alignItems: "center",
                      gap: "4px",
                      background: "rgba(168, 85, 247, 0.15)",
                      border: "1px solid #7652d6",
                      color: "#c4a9ff",
                      borderRadius: "6px",
                      padding: "4px 8px",
                      fontSize: "12px",
                      cursor: "pointer"
                    }}
                  >
                    <Sparkles size={13} /> {regeneratingQId === q.id ? "Regenerating..." : "✨ Regenerate"}
                  </button>

                  <label style={{ color: "#9292a5", fontSize: "12px" }}>Marks: </label>
                  <input
                    type="number"
                    step="0.5"
                    value={q.marks}
                    onChange={(e) => handleUpdateQuestion(qIndex, "marks", parseFloat(e.target.value) || 0)}
                    style={{ width: "60px", padding: "4px 8px", background: "#15151f", border: "1px solid #30303e", borderRadius: "6px", color: "white" }}
                  />
                  {questions.length > 1 && (
                    <button onClick={() => handleRemoveQuestion(qIndex)} style={{ background: "none", border: "none", color: "#f87171", cursor: "pointer" }}>
                      <Trash2 size={18} />
                    </button>
                  )}
                </div>
              </div>

              <input
                type="text"
                placeholder="Enter question text..."
                value={q.questionText}
                onChange={(e) => handleUpdateQuestion(qIndex, "questionText", e.target.value)}
                style={{ width: "100%", padding: "10px", background: "#15151f", border: "1px solid #30303e", borderRadius: "8px", color: "white", marginBottom: "1rem" }}
              />

              {/* MCQ Options */}
              {q.questionType === "mcq" && (
                <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                  <label style={{ color: "#9292a5", fontSize: "12px" }}>Select Correct Answer:</label>
                  {q.options.map((opt, optIdx) => (
                    <div key={optIdx} style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
                      <input
                        type="radio"
                        name={`correct-${qIndex}`}
                        checked={q.correctAnswer === opt}
                        onChange={() => handleUpdateQuestion(qIndex, "correctAnswer", opt)}
                      />
                      <input
                        type="text"
                        value={opt}
                        onChange={(e) => handleUpdateOption(qIndex, optIdx, e.target.value)}
                        style={{ flex: 1, padding: "8px", background: "#15151f", border: "1px solid #30303e", borderRadius: "6px", color: "white" }}
                      />
                    </div>
                  ))}
                </div>
              )}

              {/* Multiple Select */}
              {q.questionType === "multiple_select" && (
                <div style={{ display: "flex", flexDirection: "column", gap: "0.5rem" }}>
                  <label style={{ color: "#9292a5", fontSize: "12px" }}>Select All Correct Answers:</label>
                  {q.options.map((opt, optIdx) => {
                    const isChecked = Array.isArray(q.correctAnswer) && q.correctAnswer.includes(opt);
                    return (
                      <div key={optIdx} style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
                        <input
                          type="checkbox"
                          checked={isChecked}
                          onChange={(e) => {
                            let curr = Array.isArray(q.correctAnswer) ? [...q.correctAnswer] : [];
                            if (e.target.checked) curr.push(opt);
                            else curr = curr.filter((item) => item !== opt);
                            handleUpdateQuestion(qIndex, "correctAnswer", curr);
                          }}
                        />
                        <input
                          type="text"
                          value={opt}
                          onChange={(e) => handleUpdateOption(qIndex, optIdx, e.target.value)}
                          style={{ flex: 1, padding: "8px", background: "#15151f", border: "1px solid #30303e", borderRadius: "6px", color: "white" }}
                        />
                      </div>
                    );
                  })}
                </div>
              )}

              {/* True/False */}
              {q.questionType === "true_false" && (
                <div style={{ display: "flex", gap: "1.5rem" }}>
                  <label style={{ color: "#c5c5d1", fontSize: "13px", cursor: "pointer" }}>
                    <input
                      type="radio"
                      name={`tf-${qIndex}`}
                      checked={q.correctAnswer === "True"}
                      onChange={() => handleUpdateQuestion(qIndex, "correctAnswer", "True")}
                    /> True
                  </label>
                  <label style={{ color: "#c5c5d1", fontSize: "13px", cursor: "pointer" }}>
                    <input
                      type="radio"
                      name={`tf-${qIndex}`}
                      checked={q.correctAnswer === "False"}
                      onChange={() => handleUpdateQuestion(qIndex, "correctAnswer", "False")}
                    /> False
                  </label>
                </div>
              )}

              {/* Short Answer */}
              {q.questionType === "short_answer" && (
                <div>
                  <label style={{ color: "#9292a5", fontSize: "12px", display: "block", marginBottom: "4px" }}>Expected Sample Answer / Key Points:</label>
                  <input
                    type="text"
                    placeholder="Sample answer key for manual grading..."
                    value={q.correctAnswer || ""}
                    onChange={(e) => handleUpdateQuestion(qIndex, "correctAnswer", e.target.value)}
                    style={{ width: "100%", padding: "8px", background: "#15151f", border: "1px solid #30303e", borderRadius: "6px", color: "white" }}
                  />
                </div>
              )}

              {/* AI Explanation block */}
              {q.explanation && (
                <div style={{ marginTop: "1rem", background: "rgba(168, 85, 247, 0.08)", border: "1px dashed #7652d6", borderRadius: "8px", padding: "0.75rem 1rem", fontSize: "12.5px", color: "#d8b4fe" }}>
                  <strong>💡 AI Explanation:</strong> {q.explanation}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
